### ISSUE TITLE
Get torch._C._LinAlgError: cusolver error when running the explicit setting.

### ISSUE THREAD

**Issue by bluestyle97** [hanhung/PureCLIPNeRF#1]
Hi, thanks for your fantastic work! When I tried running the explicit configuration by `python run.py --config configs/low/exp_vit16.py --prompt "steampunk city; trending on artstation."`, I got the following error:
```
Traceback (most recent call last):
  File "run.py", line 169, in <module>
    train(args, cfg, data_dict, jax_key, writer)
  File "/group/30042/jialexu/projects/PureCLIPNeRF/train_exp.py", line 585, in train
    scene_rep_reconstruction(
  File "/group/30042/jialexu/projects/PureCLIPNeRF/train_exp.py", line 410, in scene_rep_reconstruction
    rgb = trans_strategy(rgb)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 805, in forward
    return F.perspective(img, startpoints, endpoints, self.interpolation, fill)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 676, in perspective
    coeffs = _get_perspective_coeffs(startpoints, endpoints)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 636, in _get_perspective_coeffs
    res = torch.linalg.lstsq(a_matrix, b_matrix, driver="gels").solution
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXgeqrf( handle, params, m, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(tau), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN.
```

It seems that the `RandomPerspective` transformation causes some bugs. I'm running on an A100 GPU with PyTorch 1.11.0 and CUDA 11.3, and the environment is set under your instruction. Do you have some suggestions to solve this problem? Disabling the `persp_aug` in the config file works fine, but I'm wondering how much this would influence the final results. Thanks a lot!

**Comment by hanhung** [comment]
Hm... I have not encountered this error before. However, it seems that some people have this error with cuda 11.3. You can try a newer version of cuda to see if it helps.

For `persp_aug` it can help to make the generation results of the explicit model less noisy. However, sometimes it can be hurtful to the texture sharpness. We left it on for all the explicit models in the paper. But for some prompts the results are better when turning it off.

**Comment by bluestyle97** [comment]
OK, thanks for your answer!
